apiVersion: v1
kind: Service
metadata:
  labels:
    app: nodejs
  name: nodejs
  namespace: nodejs-deployment
spec:
  ports:
  - nodePort: 30501
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nodejs
  type: NodePort